Items intergration tests
bluefire0009/Project-Process-and-Tools pull request #16
Opened 2024-10-14 17:07 UTC by JohnSpruijt2

test_items.py
test_itemlines.py
test_itemtypes.py

2024-10-15 08:32 UTC, TurboGreaser commented
connection should be in fixture

2024-10-15 08:41 UTC, TurboGreaser approved these changes

2024-10-15 17:46 UTC, bluefire0009 requested changes
Itemlines.py
 - test_get_all_item_lines
Het zou beter zijn als je eerst ook wat data toevoegd met post requests en dat test dat die data bestaat. Omdat de post endpoint niet bestaat zal die voor nu fallen, maar wanneer we herschrijven zal die wel bestaan
 - test_get_item_line_by_id
Het zou beter zijn als je eerst ook wat data toevoegd met post requests en dat test dat die data bestaat. Omdat de post endpoint niet bestaat zal die voor nu fallen, maar wanneer we herschrijven zal die wel bestaan
 - test_get_item_line_items
 Het zou beter zijn als je eerst ook wat data toevoegd met post requests en dat test dat die data bestaat. Omdat de post endpoint niet bestaat zal die voor nu fallen, maar wanneer we herschrijven zal die wel bestaan.
 - test_post_item_line
Na de post request nog een keer get all request en kijken of die daar in zit
 - test_put_item_line
Goed als die nu is
 - test_delete_item_line
 Na de delete request een get all request en testen dat die daar niet in zit

test_items.py
- test_get_all_items
Het zou beter zijn als je eerst ook wat data toevoegd met post requests en dat test dat die data bestaat. Omdat de post endpoint niet bestaat zal die voor nu fallen, maar wanneer we herschrijven zal die wel bestaan
- test_get_item_by_id
Goed als die nu is
- test_get_item_inventory
In theorie kan je proberen om ook een post request maken voor een test inventory en daarvan de item_id dezelfde maken als id van een nieuwe (met post toegevoegd) item
- test_get_item_inventory_totals
In theorie kan je proberen om ook een post request maken voor een test inventory en daarvan de item_id dezelfde maken als id van een nieuwe (met post toegevoegd) item
- test_post_item
Goed als die nu is
- test_put_item
Goed als die nu is
- test_delete_item
Na de delete request een get all request en testen dat die daar niet in zit

test_itemtypes.py
- test_get_all_item_lines
Het zou beter zijn als je eerst ook wat data toevoegd met post requests en dat test dat die data bestaat. Omdat de post endpoint niet bestaat zal die voor nu fallen, maar wanneer we herschrijven zal die wel bestaan
- test_get_item_types_by_id
Goed als die nu is
- test_get_item_type_items
Het zou beter zijn als je eerst ook wat data toevoegd met post requests en dat test dat die data bestaat. Omdat de post endpoint niet bestaat zal die voor nu fallen, maar wanneer we herschrijven zal die wel bestaan
- test_post_item_type
Nog een get request tussen delete en post request
- test_put_item_types
Goed als die nu is
- test_delete_item_type
Nog een get request tussen delete en post request

2024-10-16 19:15 UTC, bluefire0009 approved these changes

2024-10-16 19:15 UTC, merged